[en]
cloning_repository = "Cloning repository..."
repository_cloned = "Repository cloned."
link_unvalid = "The link you have entered is not valid."
error_when_cloning = "An error occurred when cloning the repo."
no_qikfile = "No qik configuration files detected."
lr_not_compatible = "The --latest-release option is not compatible with this git service."
lr_and_branch_not_compatible = "The --branch and --latest-release options are not compatible with each other."
parsing_qikfile = "Parsing Qikfile..."
warning_before_init = "Warning ! The template will be created in {CWD} !  Be careful if there is already content in it."
continue = "Continue ? (y/N) "
warning_from_owner = "Warning from the creator of the template: "
loading_questions = "Loading questions..."
message_from_owner = "Message from the template's owner:"
executing_commands = "Executing commands..."
link_arg = "The git link for the template."
branch_arg = "The branch to use for the template."
lr_arg = "Use the latest release of the template."
alias_arg = "The alias to use for the template."
init_description = "Initialize a template"
saveAlias_description = "Save a alias for a template."
description = "Qik is a CLI tool for use a Qik Template"
set_alias = "The alias \"{ALIAS}\" has been saved in the parameters."
toggleDefaultAliases_description = "Enable or disable default aliases."
toggleDefaultAliases_confirmation = "Default aliases have been {STATUS}."
disable = "disabled"
enable = "enabled"
project_name = "What is the name of your project ? "
project_name_requird = "The name of your project is required."
setalias_defaultalias_error = "The alias \"{ALIAS}\" is a default alias. You can't use it."
removeAlias_description = "Remove a alias for a template."
alias_remove_arg = "The alias to remove."
alias_remove_not_found = "The alias \"{ALIAS}\" was not found."
alias_remove_success = "The alias \"{ALIAS}\" has been removed."
sel_not_default = "A selection question has no defined choices."
you_can_choose = "You can choose: {CHOICES}"
or = "or"
select_value_not_in_choices = "The value \"{VALUE}\" is not in the choices."

[fr]
cloning_repository = "Clonage du dépôt..."
repository_cloned = "Dépôt cloné."
link_unvalid = "Le lien que vous avez entré n'est pas valide."
error_when_cloning = "Une erreur est survenue lors du clonage du dépôt."
no_qikfile = "Aucun fichier de configuration qik détecté."
lr_not_compatible = "L'option --latest-release n'est pas compatible avec ce service git."
lr_and_branch_not_compatible = "Les options --branch et --latest-release ne sont pas compatibles entre elles."
parsing_qikfile = "Analyse du fichier Qikfile..."
warning_before_init = "Attention ! Le template sera créé dans {CWD} ! Faites attention s'il y a déjà du contenu dedans."
continue = "Continuer ? (y/N) "
warning_from_owner = "Avertissement du créateur du template : "
loading_questions = "Chargement des questions..."
message_from_owner = "Message du créateur du template :"
executing_commands = "Exécution des commandes..."
link_arg = "Le lien git de la template."
branch_arg = "La branche à utiliser pour le template."
lr_arg = "Utiliser la dernière version du template."
alias_arg = "L'alias à utiliser pour la template."
init_description = "Initialiser une template"
saveAlias_description = "Sauvegarder un alias pour une template."
description = "Qik est un outil CLI pour utiliser une Template Qik"
set_alias = "L'alias \"{ALIAS}\" a été enregistré dans les paramètres."
toggleDefaultAliases_description = "Activer ou désactiver les alias par défaut."
toggleDefaultAliases_confirmation = "Les alias par défaut ont été {STATUS}."
disable = "désactivés"
enable = "activés"
project_name = "Quel est le nom de votre projet ? "
project_name_requird = "Le nom de votre projet est requis."
setalias_defaultalias_error = "L'alias \"{ALIAS}\" est un alias par défaut. Vous ne pouvez pas l'utiliser."
removeAlias_description = "Supprimer un alias pour une template."
alias_remove_arg = "L'alias à supprimer."
alias_remove_not_found = "L'alias \"{ALIAS}\" n'a pas été trouvé."
alias_remove_success = "L'alias \"{ALIAS}\" a été supprimé."
sel_not_default = "Une question de type sélection n'a pas de choix défini."
you_can_choose = "Vous pouvez choisir : {CHOICES}"
or = "ou"
select_value_not_in_choices = "La valeur \"{VALUE}\" n'est pas dans les choix."

[de]
cloning_repository = "Repository klonen..."
repository_cloned = "Repository geklont."
link_unvalid = "Der eingegebene Link ist ungültig."
error_when_cloning = "Beim Klonen des Repositorys ist ein Fehler aufgetreten."
no_qikfile = "Keine qik-Konfigurationsdateien erkannt."
lr_not_compatible = "Die Option --latest-release ist mit diesem Git-Dienst nicht kompatibel."
lr_and_branch_not_compatible = "Die Optionen --branch und --latest-release sind nicht miteinander kompatibel."
parsing_qikfile = "Qikfile wird analysiert..."
warning_before_init = "Achtung! Die Vorlage wird in {CWD} erstellt!  Seien Sie vorsichtig, wenn bereits Inhalte vorhanden sind."
continue = "Fortsetzen? (y/N) "
warning_from_owner = "Warnung vom Ersteller der Vorlage: "
loading_questions = "Fragen werden geladen..."
message_from_owner = "Nachricht vom Vorlagenbesitzer:"
executing_commands = "Befehle werden ausgeführt..."
link_arg = "Der Git-Link für die Vorlage."
branch_arg = "Der zu verwendende Zweig für die Vorlage."
lr_arg = "Verwenden Sie die neueste Version der Vorlage."
alias_arg = "Der Alias, der für die Vorlage verwendet werden soll."
init_description = "Initialisieren Sie eine Vorlage"
saveAlias_description = "Speichern Sie einen Alias für eine Vorlage."
description = "Qik ist ein CLI-Tool zum Verwenden einer Qik-Vorlage"
set_alias = "Der Alias \"{ALIAS}\" wurde in den Parametern gespeichert."
toggleDefaultAliases_description = "Standard-Aliase aktivieren oder deaktivieren."
toggleDefaultAliases_confirmation = "Standard-Aliase wurden {STATUS}."
disable = "deaktiviert"
enable = "aktiviert"
project_name = "Wie lautet der Name Ihres Projekts? "
project_name_requird = "Der Name Ihres Projekts ist erforderlich."
setalias_defaultalias_error = "Der Alias \"{ALIAS}\" ist ein Standardalias. Sie können es nicht verwenden."
removeAlias_description = "Entfernen Sie einen Alias für eine Vorlage."
alias_remove_arg = "Der zu entfernende Alias."
alias_remove_not_found = "Der Alias \"{ALIAS}\" wurde nicht gefunden."
alias_remove_success = "Der Alias \"{ALIAS}\" wurde entfernt."
sel_not_default = "Eine Auswahlfrage hat keine definierte Auswahl."
you_can_choose = "Sie können wählen: {CHOICES}"
or = "oder"
select_value_not_in_choices = "Der Wert \"{VALUE}\" ist nicht in den Auswahlmöglichkeiten."

[es]
cloning_repository = "Clonando repositorio..."
repository_cloned = "Repositorio clonado."
link_unvalid = "El enlace que ha introducido no es válido."
error_when_cloning = "Se produjo un error al clonar el repositorio."
no_qikfile = "No se detectaron archivos de configuración de qik."
lr_not_compatible = "La opción --latest-release no es compatible con este servicio git."
lr_and_branch_not_compatible = "Las opciones --branch y --latest-release no son compatibles entre sí."
parsing_qikfile = "Analizando Qikfile..."
warning_before_init = "¡Advertencia! ¡La plantilla se creará en {CWD}!  Tenga cuidado si ya hay contenido en él."
continue = "¿Continuar? (y/N) "
warning_from_owner = "Advertencia del creador de la plantilla: "
loading_questions = "Cargando preguntas..."
message_from_owner = "Mensaje del propietario de la plantilla:"
executing_commands = "Ejecutando comandos..."
link_arg = "El enlace de git para la plantilla."
branch_arg = "La rama a utilizar para la plantilla."
lr_arg = "Utilice la última versión de la plantilla."
alias_arg = "El alias a utilizar para la plantilla."
init_description = "Inicializar una plantilla"
saveAlias_description = "Guardar un alias para una plantilla."
description = "Qik es una herramienta CLI para usar una plantilla Qik"
set_alias = "El alias \"{ALIAS}\" se ha guardado en los parámetros."
toggleDefaultAliases_description = "Activar o desactivar los alias predeterminados."
toggleDefaultAliases_confirmation = "Los alias predeterminados han sido {STATUS}."
disable = "desactivados"
enable = "activados"
project_name = "¿Cuál es el nombre de tu proyecto? "
project_name_requird = "Se requiere el nombre de su proyecto."
setalias_defaultalias_error = "El alias \"{ALIAS}\" es un alias predeterminado. No puedes usarlo."
removeAlias_description = "Eliminar un alias para una plantilla."
alias_remove_arg = "El alias a eliminar."
alias_remove_not_found = "El alias \"{ALIAS}\" no se encontró."
alias_remove_success = "El alias \"{ALIAS}\" ha sido eliminado."
sel_not_default = "Una pregunta de selección no tiene opciones definidas."
you_can_choose = "Puedes elegir: {CHOICES}"
or = "o"
select_value_not_in_choices = "El valor \"{VALUE}\" no está en las opciones."
